/**
 * \file main.cpp
 * Entry point for the qSim CLI executable
 * 
 * \author Igor Siemienowicz
 * 
 * \copyright Copyright Igor Siemienowicz 2018 Distributed under the Boost
 * Software License, Version 1.0. (See accompanying file ../LICENSE_1_0.txt
 * or copy at https://www.boost.org/LICENSE_1_0.txt
 */

#include <stdexcept>
#include <iostream>

#include <qsim/qsim.h>

/**
 * \brief Entry point for the qSim CLI executable
 * 
 * \param argc The number of command-line arguments
 * 
 * \param argv The array of command-line argument strings
 */
int main(int argc, char* argv[])
{

    int result = 0;

    try
    {
        std::cout
            << "qSim Command-line Interface"
            << std::endl << "Copyright Igor Siemienowicz 2018"
            << std::endl
            << std::endl << "Boost Software License - Version 1.0 - August "
                "17th, 2003"
            << std::endl
            << std::endl << "Permission is hereby granted, free of charge, "
                "to any person or organization"
            << std::endl << "obtaining a copy of the software and "
                "accompanying documentation covered by"
            << std::endl << "this license (the \"Software\") to use, "
                "reproduce, display, distribute,"
            << std::endl << "execute, and transmit the Software, and to "
                "prepare derivative works of the"
            << std::endl << "Software, and to permit third-parties to whom "
                "the Software is furnished to"
            << std::endl << "do so, all subject to the following:"
            << std::endl
            << std::endl << "The copyright notices in the Software and this "
                "entire statement, including"
            << std::endl << "the above license grant, this restriction and "
                "the following disclaimer,"
            << std::endl << "must be included in all copies of the "
                "Software, in whole or in part, and"
            << std::endl << "all derivative works of the Software, unless "
                "such copies or derivative"
            << std::endl << "works are solely in the form of machine-"
                "executable object code generated by"
            << std::endl << "a source language processor."
            << std::endl
            << std::endl << "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT "
                "WARRANTY OF ANY KIND, EXPRESS OR"
            << std::endl << "IMPLIED, INCLUDING BUT NOT LIMITED TO THE "
                "WARRANTIES OF MERCHANTABILITY,"
            << std::endl << "FITNESS FOR A PARTICULAR PURPOSE, TITLE AND "
                "NON-INFRINGEMENT. IN NO EVENT"
            << std::endl << "SHALL THE COPYRIGHT HOLDERS OR ANYONE "
                "DISTRIBUTING THE SOFTWARE BE LIABLE"
            << std::endl << "FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN "
                "CONTRACT, TORT OR OTHERWISE,"
            << std::endl << "ARISING FROM, OUT OF OR IN CONNECTION WITH THE "
                "SOFTWARE OR THE USE OR OTHER"
            << std::endl << "DEALINGS IN THE SOFTWARE."
            << std::endl;

    }
    catch (const std::exception& error)
    {
        std::cerr << "[ERR] " << error.what() << std::endl;
        result = -1;
    }
    catch (...)
    {
        std::cerr << "[ERR] unrecognised error condition" << std::endl;
        result = -1;
    }

    return result;

}   // end main function
